// Core session management

export { type Args, parseArgs } from "./cli/args.ts";

// Config paths
export { getAgentDir, getDocsPath, getExamplesPath, getPackageDir, getReadmePath, VERSION } from "./config.ts";
export {
	type ActivitySyncResult,
	type ActivitySyncStatus,
	type SyncSessionAnalyticsOptions,
	syncSessionAnalytics,
} from "./core/activity-sync/activity-sync.ts";
export {
	ACTIVITY_SYNC_CLIENT_ID,
	ACTIVITY_SYNC_SCOPE,
	ActivitySyncApiError,
	type ActivitySyncApiOptions,
	type ActivitySyncDeviceFlowResponse,
	type ActivitySyncFetch,
	type ActivitySyncTokenResponse,
	type ActivitySyncUploadResponse,
	type ActivitySyncWatermarkResponse,
	DEFAULT_PI_DEV_URL,
	getActivitySyncWatermark,
	pollActivitySyncDeviceToken,
	refreshActivitySyncAccessToken,
	startActivitySyncDeviceFlow,
	type UploadSessionAnalyticsOptions,
	uploadSessionAnalytics,
} from "./core/activity-sync/api.ts";
export {
	ACTIVITY_SYNC_CONTENT_ENCODING,
	ACTIVITY_SYNC_MAX_COMPRESSED_BYTES,
	ACTIVITY_SYNC_MAX_DECOMPRESSED_BYTES,
	type ActivitySyncPayload,
	type BuildActivitySyncPayloadsOptions,
	buildActivitySyncPayloads,
	compareSessionAnalyticsRecords,
	getSessionAnalyticsRecordTimestamp,
	serializeSessionAnalyticsNdjson,
	sortSessionAnalyticsRecords,
} from "./core/activity-sync/payload.ts";
export {
	hashSessionAnalyticsString,
	type ProjectSessionAnalyticsOptions,
	type ProjectSessionHeaderAnalyticsOptions,
	projectSessionEntryForAnalytics,
	projectSessionForAnalytics,
	projectSessionHeaderForAnalytics,
	SESSION_ANALYTICS_SCHEMA_VERSION,
	type SessionAnalyticsContentStats,
	type SessionAnalyticsEntryRecord,
	type SessionAnalyticsRecord,
	type SessionAnalyticsSessionRecord,
	type SessionAnalyticsUsage,
} from "./core/activity-sync/session-analytics.ts";
export {
	type BuildSessionAnalyticsUploadOptions,
	type BuildSessionAnalyticsUploadResult,
	buildSessionAnalyticsUpload,
} from "./core/activity-sync/session-analytics-reader.ts";
export {
	type DiscoveredSession,
	type DiscoverSessionFilesOptions,
	type DiscoverSessionsOptions,
	discoverSessionFiles,
	discoverSessions,
	type SessionDiscoveryPhase,
	type SessionDiscoveryProgress,
	type SessionDiscoveryProgressCallback,
} from "./core/activity-sync/session-discovery.ts";
export {
	type ActivitySyncLockResult,
	type ActivitySyncState,
	type ActivitySyncStatePaths,
	getActivitySyncStatePaths,
	getStableActivitySyncDeviceId,
	loadActivitySyncState,
	saveActivitySyncState,
	updateActivitySyncState,
	withActivitySyncLock,
} from "./core/activity-sync/state.ts";
export {
	AgentSession,
	type AgentSessionConfig,
	type AgentSessionEvent,
	type AgentSessionEventListener,
	type ModelCycleResult,
	type ParsedSkillBlock,
	type PromptOptions,
	parseSkillBlock,
	type SessionStats,
} from "./core/agent-session.ts";
// Auth and model registry
export {
	type ApiKeyCredential,
	type AuthCredential,
	type AuthStatus,
	AuthStorage,
	type AuthStorageBackend,
	FileAuthStorageBackend,
	InMemoryAuthStorageBackend,
	type OAuthCredential,
} from "./core/auth-storage.ts";
// Compaction
export {
	type BranchPreparation,
	type BranchSummaryResult,
	type CollectEntriesResult,
	type CompactionResult,
	type CutPointResult,
	calculateContextTokens,
	collectEntriesForBranchSummary,
	compact,
	DEFAULT_COMPACTION_SETTINGS,
	estimateTokens,
	type FileOperations,
	findCutPoint,
	findTurnStartIndex,
	type GenerateBranchSummaryOptions,
	generateBranchSummary,
	generateSummary,
	getLastAssistantUsage,
	prepareBranchEntries,
	serializeConversation,
	shouldCompact,
} from "./core/compaction/index.ts";
export {
	createEventBus,
	type EventBus,
	type EventBusController,
} from "./core/event-bus.ts";
// Extension system
export type {
	AgentEndEvent,
	AgentStartEvent,
	AgentToolResult,
	AgentToolUpdateCallback,
	AppKeybinding,
	AutocompleteProviderFactory,
	BashToolCallEvent,
	BeforeAgentStartEvent,
	BeforeAgentStartEventResult,
	BeforeProviderRequestEvent,
	BeforeProviderRequestEventResult,
	BuildSystemPromptOptions,
	CompactOptions,
	ContextEvent,
	ContextUsage,
	CustomToolCallEvent,
	EditToolCallEvent,
	ExecOptions,
	ExecResult,
	Extension,
	ExtensionActions,
	ExtensionAPI,
	ExtensionCommandContext,
	ExtensionCommandContextActions,
	ExtensionContext,
	ExtensionContextActions,
	ExtensionError,
	ExtensionEvent,
	ExtensionFactory,
	ExtensionFlag,
	ExtensionHandler,
	ExtensionRuntime,
	ExtensionShortcut,
	ExtensionUIContext,
	ExtensionUIDialogOptions,
	ExtensionWidgetOptions,
	FindToolCallEvent,
	GrepToolCallEvent,
	InputEvent,
	InputEventResult,
	InputSource,
	KeybindingsManager,
	LoadExtensionsResult,
	LsToolCallEvent,
	MessageRenderer,
	MessageRenderOptions,
	ProjectTrustContext,
	ProjectTrustEvent,
	ProjectTrustEventDecision,
	ProjectTrustEventResult,
	ProjectTrustHandler,
	ProviderConfig,
	ProviderModelConfig,
	ReadToolCallEvent,
	RegisteredCommand,
	RegisteredTool,
	ResolvedCommand,
	SessionBeforeCompactEvent,
	SessionBeforeForkEvent,
	SessionBeforeSwitchEvent,
	SessionBeforeTreeEvent,
	SessionCompactEvent,
	SessionShutdownEvent,
	SessionStartEvent,
	SessionTreeEvent,
	SlashCommandInfo,
	SlashCommandSource,
	SourceInfo,
	TerminalInputHandler,
	ToolCallEvent,
	ToolCallEventResult,
	ToolDefinition,
	ToolExecutionMode,
	ToolInfo,
	ToolRenderResultOptions,
	ToolResultEvent,
	TurnEndEvent,
	TurnStartEvent,
	UserBashEvent,
	UserBashEventResult,
	WidgetPlacement,
	WorkingIndicatorOptions,
	WriteToolCallEvent,
} from "./core/extensions/index.ts";
export {
	createExtensionRuntime,
	defineTool,
	discoverAndLoadExtensions,
	ExtensionRunner,
	isBashToolResult,
	isEditToolResult,
	isFindToolResult,
	isGrepToolResult,
	isLsToolResult,
	isReadToolResult,
	isToolCallEventType,
	isWriteToolResult,
	wrapRegisteredTool,
	wrapRegisteredTools,
} from "./core/extensions/index.ts";
// Footer data provider (git branch + extension statuses - data not otherwise available to extensions)
export type { ReadonlyFooterDataProvider } from "./core/footer-data-provider.ts";
export { convertToLlm } from "./core/messages.ts";
export { ModelRegistry } from "./core/model-registry.ts";
export type {
	PackageManager,
	PathMetadata,
	ProgressCallback,
	ProgressEvent,
	ResolvedPaths,
	ResolvedResource,
} from "./core/package-manager.ts";
export { DefaultPackageManager } from "./core/package-manager.ts";
export {
	formatPiDevScopes,
	getPiDevBaseUrl,
	normalizePiDevBaseUrl,
	PI_DEV_ACTIVITY_SYNC_SCOPE,
	PI_DEV_DEFAULT_BASE_URL,
	PI_DEV_OAUTH_CLIENT_ID,
	PI_DEV_OAUTH_PROVIDER_ID,
	PI_DEV_OFFLINE_ACCESS_SCOPE,
	PI_DEV_PROFILE_CONNECTED_STATUS,
	PI_DEV_PROFILE_SCOPES,
	PI_DEV_SESSION_SHARE_SCOPE,
	PI_DEV_SETUP_PROFILE_CONNECTED_STATUS,
	scopesFromString,
	withPiDevOfflineAccess,
} from "./core/pi-dev/config.ts";
export {
	createFormBody,
	getPiDevApiUrl,
	getPiDevFetch,
	isRecord,
	numberField,
	PiDevApiError,
	type PiDevApiErrorCtor,
	type PiDevApiOptions,
	type PiDevFetch,
	readJson,
	readJsonObject,
	requireNumber,
	requireString,
	stringField,
	throwIfPiDevNotOk,
} from "./core/pi-dev/http.ts";
export {
	getPiDevAuth,
	hasPiDevScopes,
	introspectPiDevAccessToken,
	loginPiDev,
	type PiDevAccessIntrospectionResult,
	type PiDevAuthOptions,
	type PiDevAuthResult,
	type PiDevDeviceCodeInfo,
	type PiDevDeviceFlowOptions,
	type PiDevDeviceFlowResponse,
	type PiDevDeviceTokenOptions,
	type PiDevLoginOptions,
	type PiDevRefreshTokenOptions,
	type PiDevTokenResponse,
	pollPiDevDeviceToken,
	refreshPiDevAccessToken,
	startPiDevDeviceFlow,
} from "./core/pi-dev/oauth.ts";
export {
	formatPiDevShareSuccess,
	formatPiDevShareUploadError,
	getPiDevShareAuth,
	loginPiDevShare,
	type PiDevShareAuthResult,
	type PiDevShareDeviceAuthInfo,
	type PiDevShareDeviceAuthOptions,
	type PiDevShareUploadOptions,
	type PiDevShareUploadResult,
	parseShareCommand,
	type ShareCommandMode,
	type ShareCommandParseResult,
	uploadPiDevSessionShare,
} from "./core/pi-dev/session-share.ts";
export type {
	ResourceCollision,
	ResourceDiagnostic,
	ResourceLoader,
} from "./core/resource-loader.ts";
export {
	DefaultResourceLoader,
	loadProjectContextFiles,
} from "./core/resource-loader.ts";
// SDK for programmatic usage
export {
	AgentSessionRuntime,
	type AgentSessionRuntimeDiagnostic,
	type AgentSessionServices,
	type CreateAgentSessionFromServicesOptions,
	type CreateAgentSessionOptions,
	type CreateAgentSessionResult,
	type CreateAgentSessionRuntimeFactory,
	type CreateAgentSessionRuntimeResult,
	type CreateAgentSessionServicesOptions,
	// Factory
	createAgentSession,
	createAgentSessionFromServices,
	createAgentSessionRuntime,
	createAgentSessionServices,
	createBashTool,
	// Tool factories (for custom cwd)
	createCodingTools,
	createEditTool,
	createFindTool,
	createGrepTool,
	createLsTool,
	createReadOnlyTools,
	createReadTool,
	createWriteTool,
	type PromptTemplate,
} from "./core/sdk.ts";

export {
	type BranchSummaryEntry,
	buildSessionContext,
	type CompactionEntry,
	CURRENT_SESSION_VERSION,
	type CustomEntry,
	type CustomMessageEntry,
	type FileEntry,
	getLatestCompactionEntry,
	type ModelChangeEntry,
	migrateSessionEntries,
	type NewSessionOptions,
	parseSessionEntries,
	type SessionContext,
	type SessionEntry,
	type SessionEntryBase,
	type SessionHeader,
	type SessionInfo,
	type SessionInfoEntry,
	SessionManager,
	type SessionMessageEntry,
	type ThinkingLevelChangeEntry,
} from "./core/session-manager.ts";
export {
	type CompactionSettings,
	type ImageSettings,
	type PackageSource,
	type PiDevActivitySyncSettings,
	type PiDevSettings,
	type RetrySettings,
	SettingsManager,
	type SettingsManagerCreateOptions,
	type TelemetrySettings,
} from "./core/settings-manager.ts";
// Skills
export {
	formatSkillsForPrompt,
	type LoadSkillsFromDirOptions,
	type LoadSkillsResult,
	loadSkills,
	loadSkillsFromDir,
	type Skill,
	type SkillFrontmatter,
} from "./core/skills.ts";
export { createSyntheticSourceInfo } from "./core/source-info.ts";
// Tools
export {
	type BashOperations,
	type BashSpawnContext,
	type BashSpawnHook,
	type BashToolDetails,
	type BashToolInput,
	type BashToolOptions,
	createBashToolDefinition,
	createEditToolDefinition,
	createFindToolDefinition,
	createGrepToolDefinition,
	createLocalBashOperations,
	createLsToolDefinition,
	createReadToolDefinition,
	createWriteToolDefinition,
	DEFAULT_MAX_BYTES,
	DEFAULT_MAX_LINES,
	type EditOperations,
	type EditToolDetails,
	type EditToolInput,
	type EditToolOptions,
	type FindOperations,
	type FindToolDetails,
	type FindToolInput,
	type FindToolOptions,
	formatSize,
	type GrepOperations,
	type GrepToolDetails,
	type GrepToolInput,
	type GrepToolOptions,
	type LsOperations,
	type LsToolDetails,
	type LsToolInput,
	type LsToolOptions,
	type ReadOperations,
	type ReadToolDetails,
	type ReadToolInput,
	type ReadToolOptions,
	type ToolsOptions,
	type TruncationOptions,
	type TruncationResult,
	truncateHead,
	truncateLine,
	truncateTail,
	type WriteOperations,
	type WriteToolInput,
	type WriteToolOptions,
	withFileMutationQueue,
} from "./core/tools/index.ts";
export {
	hasProjectTrustInputs,
	type ProjectTrustDecision,
	ProjectTrustStore,
} from "./core/trust-manager.ts";
// Main entry point
export { type MainOptions, main } from "./main.ts";
// Run modes for programmatic SDK usage
export {
	InteractiveMode,
	type InteractiveModeOptions,
	type ModelInfo,
	type PrintModeOptions,
	RpcClient,
	type RpcClientOptions,
	type RpcCommand,
	type RpcEventListener,
	type RpcExtensionUIRequest,
	type RpcExtensionUIResponse,
	type RpcResponse,
	type RpcSessionState,
	runPrintMode,
	runRpcMode,
} from "./modes/index.ts";
// UI components for extensions
export {
	ArminComponent,
	AssistantMessageComponent,
	BashExecutionComponent,
	BorderedLoader,
	BranchSummaryMessageComponent,
	CompactionSummaryMessageComponent,
	CustomEditor,
	CustomMessageComponent,
	DynamicBorder,
	ExtensionEditorComponent,
	ExtensionInputComponent,
	ExtensionSelectorComponent,
	FooterComponent,
	keyHint,
	keyText,
	LoginDialogComponent,
	ModelSelectorComponent,
	OAuthSelectorComponent,
	type RenderDiffOptions,
	rawKeyHint,
	renderDiff,
	SessionSelectorComponent,
	type SettingsCallbacks,
	type SettingsConfig,
	SettingsSelectorComponent,
	ShowImagesSelectorComponent,
	SkillInvocationMessageComponent,
	ThemeSelectorComponent,
	ThinkingSelectorComponent,
	ToolExecutionComponent,
	type ToolExecutionOptions,
	TreeSelectorComponent,
	truncateToVisualLines,
	UserMessageComponent,
	UserMessageSelectorComponent,
	type VisualTruncateResult,
} from "./modes/interactive/components/index.ts";
// Theme utilities for custom tools and extensions
export {
	getLanguageFromPath,
	getMarkdownTheme,
	getSelectListTheme,
	getSettingsListTheme,
	highlightCode,
	initTheme,
	Theme,
	type ThemeColor,
} from "./modes/interactive/theme/theme.ts";
// Clipboard utilities
export { copyToClipboard } from "./utils/clipboard.ts";
export { parseFrontmatter, stripFrontmatter } from "./utils/frontmatter.ts";
export { convertToPng } from "./utils/image-convert.ts";
export {
	formatDimensionNote,
	type ResizedImage,
	resizeImage,
} from "./utils/image-resize.ts";
// Shell utilities
export { getShellConfig } from "./utils/shell.ts";
